<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>cc3bb6f2-4fb7-447e-9451-4b3c36a33a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
