<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstImage</name>
   <tag></tag>
   <elementGuidId>3f7ba0e4-7dfe-4d8d-893c-36b0a5fdd79a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.figure</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
